### ISSUE TITLE
[Feature request] Exclude apps from being detected by DRP_Creative

### ISSUE THREAD

**Issue by ddomino007** [djkato/DRP_Creative#13]
Hello! Some apps already have tools for Rich Presence
i.e. a tool exists for FL Studio + Blender has the Blendpresence addon
I'd love for the tool to have an ability to have an ignore list of programs it should ignore so that it does not spawn a presence, in case someone is using a different integration to handle it for them.
I got this mainly for Substance Painter and now it detects my Blender, and i have dual presences because I have Blendpresence running.
I know I could remove Blendpresence but i like it's display more - displays the mode, rendering etc. (and there's a typo in the default Blender project name.)

**Comment by djkato** [comment]
Good idea! I don't use windows anymore though, so it might take me time to get around to it again. For now, I wonder what happens if you directly modify your settings toml file so that the keyword list includes blender, and the list mode is in exclude?
```toml
keywords_list = ["Blender"]
show_default_when_excluded = false
should_list_include_or_exclude = "Exclude"
```
